### ISSUE TITLE
Communication workflow - unable to save Related Consultation/Details step

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#911]
**Describe the issue** - Unable to save the Related Consultation/Details step in the Communication workflow - an error occurs and you cannot move on to the next step.

**Steps to reproduce**

1) Open a new Communication workflow

2) Enter data for Related Consultation, Communication Date, Subject, and Type

3) Click the Save and Continue button - saving error occurs:

![image](https://user-images.githubusercontent.com/78143228/164199445-70876862-1d7d-4de3-9c45-cb4800a171b8.png)

**Comment by chiatt** [comment]
Unfortunately I haven't been able to reproduce this error. Is there an error message in the logs that you might be getting?

**Comment by rlwilliamss** [comment]
We're still getting this error following the latest changes so it has been raised internally. I'm getting this console error:

![image](https://user-images.githubusercontent.com/78143228/166942274-714673b4-9a22-4e4d-8fc2-6f9c76895c3f.png)

**Comment by chiatt** [comment]
Thanks @rlwilliamss, I gave it another shot, but I'm still not getting this error. The issue seems to be data related based on your screenshot because it's occurring when hitting the `/api/tiles` endpoint. Would you be able to look at the server logs (django or apache)? There could be a message there that might provide some clues to what's causing this.

**Comment by aj-he** [comment]
@chiatt @rlwilliamss the issue seems to be to do with the auto node populate function that has been attached to the comms card in our environment. Removing the function from the card fixes the issues. @rlwilliamss please raise as a auto pop node bug on the tile api on our internal ticket list. Closing
